# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96c550ca9b1b681d1fa2bb610004843eb406a1c06c61ee519951c3c3420ebe4528e715783f430da628a0663b429dfa9921b651f811df9172233d5383b55364c3

test:
  secret_key_base: a207d7d4ad37ef3a925dfc5f82d5e0fb12e14a92543770f1389b0c3e5c936f94f1ca86d86fa817eb1aae19f27c289a27c7f13d445fc6c64e5948bda3e38a2df9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
