require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ModifiersController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Modifier. As you add validations to Modifier, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ModifiersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all modifiers as @modifiers" do
      modifier = Modifier.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:modifiers)).to eq([modifier])
    end
  end

  describe "GET #show" do
    it "assigns the requested modifier as @modifier" do
      modifier = Modifier.create! valid_attributes
      get :show, {:id => modifier.to_param}, valid_session
      expect(assigns(:modifier)).to eq(modifier)
    end
  end

  describe "GET #new" do
    it "assigns a new modifier as @modifier" do
      get :new, {}, valid_session
      expect(assigns(:modifier)).to be_a_new(Modifier)
    end
  end

  describe "GET #edit" do
    it "assigns the requested modifier as @modifier" do
      modifier = Modifier.create! valid_attributes
      get :edit, {:id => modifier.to_param}, valid_session
      expect(assigns(:modifier)).to eq(modifier)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Modifier" do
        expect {
          post :create, {:modifier => valid_attributes}, valid_session
        }.to change(Modifier, :count).by(1)
      end

      it "assigns a newly created modifier as @modifier" do
        post :create, {:modifier => valid_attributes}, valid_session
        expect(assigns(:modifier)).to be_a(Modifier)
        expect(assigns(:modifier)).to be_persisted
      end

      it "redirects to the created modifier" do
        post :create, {:modifier => valid_attributes}, valid_session
        expect(response).to redirect_to(Modifier.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved modifier as @modifier" do
        post :create, {:modifier => invalid_attributes}, valid_session
        expect(assigns(:modifier)).to be_a_new(Modifier)
      end

      it "re-renders the 'new' template" do
        post :create, {:modifier => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested modifier" do
        modifier = Modifier.create! valid_attributes
        put :update, {:id => modifier.to_param, :modifier => new_attributes}, valid_session
        modifier.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested modifier as @modifier" do
        modifier = Modifier.create! valid_attributes
        put :update, {:id => modifier.to_param, :modifier => valid_attributes}, valid_session
        expect(assigns(:modifier)).to eq(modifier)
      end

      it "redirects to the modifier" do
        modifier = Modifier.create! valid_attributes
        put :update, {:id => modifier.to_param, :modifier => valid_attributes}, valid_session
        expect(response).to redirect_to(modifier)
      end
    end

    context "with invalid params" do
      it "assigns the modifier as @modifier" do
        modifier = Modifier.create! valid_attributes
        put :update, {:id => modifier.to_param, :modifier => invalid_attributes}, valid_session
        expect(assigns(:modifier)).to eq(modifier)
      end

      it "re-renders the 'edit' template" do
        modifier = Modifier.create! valid_attributes
        put :update, {:id => modifier.to_param, :modifier => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested modifier" do
      modifier = Modifier.create! valid_attributes
      expect {
        delete :destroy, {:id => modifier.to_param}, valid_session
      }.to change(Modifier, :count).by(-1)
    end

    it "redirects to the modifiers list" do
      modifier = Modifier.create! valid_attributes
      delete :destroy, {:id => modifier.to_param}, valid_session
      expect(response).to redirect_to(modifiers_url)
    end
  end

end
